name: ci

on: [push, pull_request]

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: dns
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # checkout tags so version in Manifest is set properly
    - name: Build ${{ matrix.config.image }}
      run: make "prestodev/${{ matrix.config.image }}"
    - name: Test ${{ matrix.config.test }}
      if: ${{ matrix.config.test  != '' }}
      shell: 'script -q -e -c "bash {0}"'
      run: echo Ran
